// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// A is an autogenerated mock type for the A type
type A struct {
	mock.Mock
}

// A provides a mock function with given fields:
func (_m *A) A() {
	_m.Called()
}
