// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// B is an autogenerated mock type for the B type
type B struct {
	mock.Mock
}

// B provides a mock function with given fields:
func (_m *B) B() {
	_m.Called()
}
