// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "ownergit/external_libs/gomockery/domain"

	mock "github.com/stretchr/testify/mock"
)

// C is an autogenerated mock type for the C type
type C struct {
	mock.Mock
}

// CreateB provides a mock function with given fields: a
func (_m *C) CreateB(a domain.A) domain.B {
	ret := _m.Called(a)

	var r0 domain.B
	if rf, ok := ret.Get(0).(func(domain.A) domain.B); ok {
		r0 = rf(a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.B)
		}
	}

	return r0
}
