// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/liocheng/Install/go_path/src/ownergit/advance/cgo/c_2_go/main.go:1:1
package main

//int sum(int a, int b);
import _ "unsafe"

//export sum
func sum(a, b  /*line :7:15*/_Ctype_int /*line :7:20*/)  /*line :7:22*/_Ctype_int /*line :7:27*/ {
	return a + b
}

/*
// $ go build -buildmode=c-archive -o sum.a main.go
go tool cgo main.go
*/

func main() {}
