// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/liocheng/Install/go_path/src/ownergit/advance/cgo/main.go:1:1
package main

/*
#include <stdint.h>
#include <errno.h>

//div
int div(int a, int b) {
	if (b == 0) {
		errno = EINVAL;
		return 0;
	}

	return a / b;
}

// 定义一个 C 语言函数，用于两个整数相加
int add(int a, int b) {
    return a + b;
}
*/
import _ "unsafe"
import "fmt"

func main() {
	// 定义两个 Go 语言中的整数
	a, b := 3, 4

	// 调用 C 语言中的 add 函数
	result := ( /*line :30:12*/_Cfunc_add /*line :30:16*/)( /*line :30:18*/_Ctype_int /*line :30:23*/(a),  /*line :30:28*/_Ctype_int /*line :30:33*/(b))

	// 将结果从 C 类型转换为 Go 类型，并打印出来
	fmt.Printf("The result of adding %d and %d is %d\n", a, b, int(result))

	v, err := ( /*line :35:12*/_C2func_div /*line :35:16*/)(2, 1)
	fmt.Println(v, err)

	v, err = ( /*line :38:11*/_C2func_div /*line :38:15*/)(1, 0)
	fmt.Println(v, err)
}
