// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/liocheng/Install/go_path/src/ownergit/advance/cgo/go_2_c/main.go:1:1
package main

//int sum(int a, int b) { return a+b; }
import _ "unsafe"

/*
$ go tool cgo main.go
*/
func main() {
	println(( /*line :10:10*/_Cfunc_sum /*line :10:14*/)(1, 1))
}
