// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package echo

import (
	"context"
	"fmt"
)

type Request struct {
	Msg string `thrift:"Msg,1" frugal:"1,default,string" json:"Msg"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetMsg() (v string) {
	return p.Msg
}
func (p *Request) SetMsg(val string) {
	p.Msg = val
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1: "Msg",
}

type Response struct {
	Msg string `thrift:"Msg,1" frugal:"1,default,string" json:"Msg"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetMsg() (v string) {
	return p.Msg
}
func (p *Response) SetMsg(val string) {
	p.Msg = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "Msg",
}

type EchoService interface {
	Echo(ctx context.Context, req *Request) (r *Response, err error)

	VisitOneway(ctx context.Context, req *Request) (err error)
}

type EchoServiceEchoArgs struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewEchoServiceEchoArgs() *EchoServiceEchoArgs {
	return &EchoServiceEchoArgs{}
}

func (p *EchoServiceEchoArgs) InitDefault() {
}

var EchoServiceEchoArgs_Req_DEFAULT *Request

func (p *EchoServiceEchoArgs) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return EchoServiceEchoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EchoServiceEchoArgs) SetReq(val *Request) {
	p.Req = val
}

func (p *EchoServiceEchoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoServiceEchoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoArgs(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoArgs = map[int16]string{
	1: "req",
}

type EchoServiceEchoResult struct {
	Success *Response `thrift:"success,0,optional" frugal:"0,optional,Response" json:"success,omitempty"`
}

func NewEchoServiceEchoResult() *EchoServiceEchoResult {
	return &EchoServiceEchoResult{}
}

func (p *EchoServiceEchoResult) InitDefault() {
}

var EchoServiceEchoResult_Success_DEFAULT *Response

func (p *EchoServiceEchoResult) GetSuccess() (v *Response) {
	if !p.IsSetSuccess() {
		return EchoServiceEchoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *EchoServiceEchoResult) SetSuccess(x interface{}) {
	p.Success = x.(*Response)
}

func (p *EchoServiceEchoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoServiceEchoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceEchoResult(%+v)", *p)
}

var fieldIDToName_EchoServiceEchoResult = map[int16]string{
	0: "success",
}

type EchoServiceVisitOnewayArgs struct {
	Req *Request `thrift:"req,1" frugal:"1,default,Request" json:"req"`
}

func NewEchoServiceVisitOnewayArgs() *EchoServiceVisitOnewayArgs {
	return &EchoServiceVisitOnewayArgs{}
}

func (p *EchoServiceVisitOnewayArgs) InitDefault() {
}

var EchoServiceVisitOnewayArgs_Req_DEFAULT *Request

func (p *EchoServiceVisitOnewayArgs) GetReq() (v *Request) {
	if !p.IsSetReq() {
		return EchoServiceVisitOnewayArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EchoServiceVisitOnewayArgs) SetReq(val *Request) {
	p.Req = val
}

func (p *EchoServiceVisitOnewayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoServiceVisitOnewayArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EchoServiceVisitOnewayArgs(%+v)", *p)
}

var fieldIDToName_EchoServiceVisitOnewayArgs = map[int16]string{
	1: "req",
}
